"""empty message

Revision ID: f8b0701109ee
Revises: 
Create Date: 2020-03-01 21:06:43.463245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b0701109ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('nickname', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('pw_secure_question', sa.String(length=50), nullable=False),
    sa.Column('pw_secure_answer', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('nickname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_info')
    # ### end Alembic commands ###
